[package]
name = "TQuill"
version = "0.1.0"
edition = "2024"

[dependencies]
syntect = "5.3.0"
color-eyre = "0.6.3"
crossterm = "0.28.1"
ratatui = { version = "0.30.0", features = ["serde"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
